### ISSUE TITLE
XDG base directory spec

### ISSUE THREAD

**Issue by dchinmay2** [agrawal-d/moodle-cms-notifs#1]
If you're fine with platform-specific code then I can implement the [XDG base directory](https://specifications.freedesktop.org/basedir-spec/latest/index.html) spec for Linux. The latest version also includes a directory for logs (https://www.reddit.com/r/linux/comments/ny34vs/new_xdg_state_home_in_xdg_base_directory_spec/)

**Comment by agrawal-d** [comment]
Sure, go ahead, I'd love to see a PR! In the PR, please make sure:

-  that the application still works for other platforms, like Windows / MacOS.
- to document the location of the config file in the readme ( for each platform ).
- the app does not break on Linuxes without XDG.

Thanks!

**Comment by dchinmay2** [comment]
Nice, I'm planning to add a check for Linux and leaving the rest as it is. If it is Linux, then:

- If the envvars are set then we have XDG and use those vars
- If the envvars are not set, then we use the default XDG locations (`~/.config` for config and `~/.local/state` for logs). Whether or not the distro does XDG does not matter in this case.

Is this fine?

**Comment by agrawal-d** [comment]
Sounds good.
